/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package consultorio.gui;

import consultorio.basededatos.ConexionDB;
import consultorio.paciente.Fecha;
import consultorio.paciente.Historial;
import javax.swing.JOptionPane;

/**
 *
 * @author marin
 */
public class AddHist extends javax.swing.JFrame {

    /**
     * Creates new form AddHist
     */
    public AddHist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelHistorial = new javax.swing.JLabel();
        jLabelPadAct = new javax.swing.JLabel();
        jTFPadAct = new javax.swing.JTextField();
        jLabelExLab = new javax.swing.JLabel();
        jTFExLab = new javax.swing.JTextField();
        jLabelExImg = new javax.swing.JLabel();
        jTFExImg = new javax.swing.JTextField();
        jLabelTratamiento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTATratamiento = new javax.swing.JTextArea();
        jLabelComentarios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLSeguimiento = new javax.swing.JLabel();
        jCBdia = new javax.swing.JComboBox();
        jCBmes = new javax.swing.JComboBox();
        jTFanio = new javax.swing.JTextField();
        jButtonAcep = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Historial - MediHist v0.1");
        setResizable(false);

        jLabelHistorial.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabelHistorial.setText("Historial");

        jLabelPadAct.setText("Padecimiento Actual:");

        jLabelExLab.setText("Examen Laboratorio:");

        jLabelExImg.setText("Examen Imagen:");

        jLabelTratamiento.setText("Tratamiento: ");

        jTATratamiento.setColumns(20);
        jTATratamiento.setRows(5);
        jScrollPane1.setViewportView(jTATratamiento);

        jLabelComentarios.setText("Comentarios:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLSeguimiento.setText("Fecha Seguimiento:");

        jCBdia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "d", "1", "2", "3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31" }));
        jCBdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBdiaActionPerformed(evt);
            }
        });

        jCBmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "m", "1", "2", "3","4","5","6","7","8","9","10","11","12"}));

        jButtonAcep.setText("Aceptar");
        jButtonAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPadAct)
                        .addGap(18, 18, 18)
                        .addComponent(jTFPadAct))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelExLab)
                            .addComponent(jLabelHistorial)
                            .addComponent(jLabelExImg)
                            .addComponent(jLabelTratamiento)
                            .addComponent(jLabelComentarios)
                            .addComponent(jLSeguimiento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jTFExLab)
                            .addComponent(jTFExImg)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jCBdia, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBmes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFanio)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAcep)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPadAct)
                    .addComponent(jTFPadAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExLab)
                    .addComponent(jTFExLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExImg)
                    .addComponent(jTFExImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTratamiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComentarios)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSeguimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAcep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    
    
    private void jCBdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBdiaActionPerformed

    private void jButtonAcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcepActionPerformed
        // TODO add your handling code here:
       try{ 
        Historial hist = new Historial();
        hist.setId_paciente(getId());
        hist.setPadActual(jTFPadAct.getText());
        hist.setExLab(jTFExLab.getText());
        hist.setExImg(jTFExImg.getText());
        hist.setTratamiento(jTATratamiento.getText());
        hist.setComentarios(jTextArea1.getText());
        hist.setSeguimiento(new Fecha(
                Integer.parseInt(String.valueOf(jCBdia.getSelectedItem())),
                Integer.parseInt(String.valueOf(jCBmes.getSelectedItem())), 
                Integer.parseInt(jTFanio.getText())));
        ConexionDB.altaHistorial(hist);
        this.dispose();
       }catch(IllegalArgumentException e){
           JOptionPane.showMessageDialog(null, e, "MediHist v0.1", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jButtonAcepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddHist().setVisible(true);
            }
        });
    }
    
    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcep;
    private javax.swing.JComboBox jCBdia;
    private javax.swing.JComboBox jCBmes;
    private javax.swing.JLabel jLSeguimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelComentarios;
    private javax.swing.JLabel jLabelExImg;
    private javax.swing.JLabel jLabelExLab;
    private javax.swing.JLabel jLabelHistorial;
    private javax.swing.JLabel jLabelPadAct;
    private javax.swing.JLabel jLabelTratamiento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTATratamiento;
    private javax.swing.JTextField jTFExImg;
    private javax.swing.JTextField jTFExLab;
    private javax.swing.JTextField jTFPadAct;
    private javax.swing.JTextField jTFanio;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
