/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package consultorio.gui;

import consultorio.basededatos.ConexionDB;
import java.util.ArrayList;
import javax.swing.JTabbedPane;

/**
 *
 * @author marin
 */
public class InfoDetallada extends javax.swing.JFrame {

    /**
     * Creates new form InfoDetallada
     */
    public InfoDetallada() {
        initComponents();
    }
    
    /**
     * Constructor para que de inicio obtenga los TextAreas llenos.
     * @param idDato id del paciente a llenar TextAreas
     */
    public InfoDetallada(String idDato) {
        initComponents();
        this.llenaTextAreas(ConexionDB.obtenerDatosPacientes(idDato));
    }
    
    private void llenaTextAreas(ArrayList<String> dP){
            String sexo = ("0".equals(dP.get(4)))?"F":"M";
            String diabetes = ("0".equals(dP.get(12)))?"No":"Si";
            String hipertension = ("0".equals(dP.get(13)))?"No":"Si";
            String tabaco = ("0".equals(dP.get(14)))?"No":"Si";
            String alcohol =("0".equals(dP.get(15)))?"No":"Si";
            String formatPersonales = "Nombre: "+dP.get(1)+" "+dP.get(2)+" "+dP.get(3)
            +"\nNacimiento: "+dP.get(10)+"\tEdad: "+dP.get(11)+" años  Sexo: "+sexo+"\nEstado Civil: "+dP.get(5)+"\t"
            + "Ocupacion: "+dP.get(6)+"\nTelefono: "+dP.get(7)+"\tCelular: "+dP.get(8)+"\n"
            + "Email: "+dP.get(9);
            String formatPatologicos = "Diabetes:"+diabetes+"\nHiperTension:"+hipertension+"\n"
                    + "Fuma:"+tabaco+"\nBebe:"+alcohol+"\nOtros:"+dP.get(16);
            String formatNoPatologicos = "Peso: "+dP.get(22)+"kg \nTalla: "+dP.get(23)+"\nTipo de Sangre: "+dP.get(24)+"\nFrecuencia Cardiaca: "+dP.get(25)
                    +"\nTension Arterial: "+dP.get(26)+"\nFrecuencia Respiratoria: "+dP.get(27)+"\nOtros: "+dP.get(28);
            String formatAlergias = "Medicamentos: "+dP.get(17)+"\nSustancias: "+dP.get(18)+"\nAlimentos: "+dP.get(19)
                    + "\nOtras: "+dP.get(20);
            
            jTAGral.setText(formatPersonales);
            jTAPat.setText(formatPatologicos);
            jTANoPat.setText(formatNoPatologicos);
            jTAAlergias.setText(formatAlergias);
    }


    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLGral = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAGral = new javax.swing.JTextArea();
        jLPat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAPat = new javax.swing.JTextArea();
        jLNoPat = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTANoPat = new javax.swing.JTextArea();
        jLAlergias = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAAlergias = new javax.swing.JTextArea();
        jBAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medi Hist - Informacion detallada del Paciente");
        setResizable(false);

        jLGral.setText("Datos Personales:");

        jTAGral.setEditable(false);
        jTAGral.setColumns(20);
        jTAGral.setRows(5);
        jScrollPane1.setViewportView(jTAGral);

        jLPat.setText("Antecedentes Patologicos");

        jTAPat.setEditable(false);
        jTAPat.setColumns(20);
        jTAPat.setRows(5);
        jScrollPane2.setViewportView(jTAPat);

        jLNoPat.setText("Antecedentes No Patologicos");

        jTANoPat.setEditable(false);
        jTANoPat.setColumns(20);
        jTANoPat.setRows(5);
        jScrollPane3.setViewportView(jTANoPat);

        jLAlergias.setText("Alergias");

        jTAAlergias.setEditable(false);
        jTAAlergias.setColumns(20);
        jTAAlergias.setRows(5);
        jScrollPane4.setViewportView(jTAAlergias);

        jBAceptar.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/consultorio/gui/logoMediHist4.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        jLabel2.setText("Informacion Detallada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLPat)
                                .addGap(121, 121, 121)
                                .addComponent(jLNoPat))
                            .addComponent(jLAlergias)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)))))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLGral)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLGral)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPat)
                    .addComponent(jLNoPat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLAlergias)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        jLabel2.setText("Informaci\u00f3n Detallada");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBAceptarActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoDetallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoDetallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoDetallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoDetallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoDetallada().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JLabel jLAlergias;
    private javax.swing.JLabel jLGral;
    private javax.swing.JLabel jLNoPat;
    private javax.swing.JLabel jLPat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTAAlergias;
    private javax.swing.JTextArea jTAGral;
    private javax.swing.JTextArea jTANoPat;
    private javax.swing.JTextArea jTAPat;
    // End of variables declaration//GEN-END:variables
}
