/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package consultorio.gui;

import consultorio.basededatos.ConexionDB;
import consultorio.paciente.Paciente;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author marin
 */
public class VentanaAltas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAltas
     */
    public VentanaAltas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLApellido1 = new javax.swing.JLabel();
        jTFAp1 = new javax.swing.JTextField();
        jLApellido2 = new javax.swing.JLabel();
        jTFAp2 = new javax.swing.JTextField();
        jLNac = new javax.swing.JLabel();
        jCBdia = new javax.swing.JComboBox();
        jLSexo = new javax.swing.JLabel();
        jRBMasculino = new javax.swing.JRadioButton();
        jRBFemenino = new javax.swing.JRadioButton();
        jLEstadoCiv = new javax.swing.JLabel();
        jTFEstCiv = new javax.swing.JTextField();
        jLOcupacion = new javax.swing.JLabel();
        jTFOcupacion = new javax.swing.JTextField();
        jLTel = new javax.swing.JLabel();
        jTFTel = new javax.swing.JTextField();
        jLCel = new javax.swing.JLabel();
        jTFCel = new javax.swing.JTextField();
        jLEmail = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jCBmes = new javax.swing.JComboBox();
        jTFAnio = new javax.swing.JTextField();
        jBotonGAceptar = new javax.swing.JButton();
        datosPers = new javax.swing.JLabel();
        antPatLabel = new javax.swing.JLabel();
        diabetesRbutton = new javax.swing.JRadioButton();
        hipertensionRButton = new javax.swing.JRadioButton();
        tabacoRButton = new javax.swing.JRadioButton();
        alcoholRButton = new javax.swing.JRadioButton();
        otroAntLabel = new javax.swing.JLabel();
        otrosPatTField = new javax.swing.JTextField();
        alergiasLabel = new javax.swing.JLabel();
        antNoPatLabel = new javax.swing.JLabel();
        pesoLabel = new javax.swing.JLabel();
        pesoTField = new javax.swing.JTextField();
        tallaLabel = new javax.swing.JLabel();
        tallaTField = new javax.swing.JTextField();
        sangreLabel = new javax.swing.JLabel();
        sangreTField = new javax.swing.JTextField();
        frecCardLabel = new javax.swing.JLabel();
        frecCardTField = new javax.swing.JTextField();
        tensArtLabel = new javax.swing.JLabel();
        tenArtTField = new javax.swing.JTextField();
        FrecRespLabel = new javax.swing.JLabel();
        frecRespTField = new javax.swing.JTextField();
        gineLabel = new javax.swing.JLabel();
        gineTField = new javax.swing.JTextField();
        otroNoPatLabel = new javax.swing.JLabel();
        otrosNoPatTFeld = new javax.swing.JTextField();
        medicaAlergiasLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mediTextArea = new javax.swing.JTextArea();
        sustanciasLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sustanciasTextArea = new javax.swing.JTextArea();
        alimentosLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alimentosTextArea = new javax.swing.JTextArea();
        otrasLabelAlergias = new javax.swing.JLabel();
        otrasAlergiasTField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MediHist - Fomulario Paciente");

        jLNombre.setText("Nombre(s):");

        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreKeyTyped(evt);
            }
        });

        jLApellido1.setText("Apellido Pat.");

        jTFAp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAp1ActionPerformed(evt);
            }
        });

        jLApellido2.setText("Apellido Mat.");

        jLNac.setText("Fecha de Nacimiento:");

        jCBdia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "d", "1", "2", "3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"}));
        jCBdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBdiaActionPerformed(evt);
            }
        });

        jLSexo.setText("Sexo:");

        jRBMasculino.setText("M");
        jRBMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMasculinoActionPerformed(evt);
            }
        });

        jRBFemenino.setText("F");
        jRBFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFemeninoActionPerformed(evt);
            }
        });

        jLEstadoCiv.setText("Estado Civil:");

        jLOcupacion.setText("Ocupacion:");

        jLTel.setText("Telefono:");

        jLCel.setText("Celular:");

        jLEmail.setText("Email:");

        jCBmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "m", "1", "2", "3","4","5","6","7","8","9","10","11","12"}));
        jCBmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmesActionPerformed(evt);
            }
        });

        jTFAnio.setText("a");
        jTFAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAnioKeyTyped(evt);
            }
        });

        jBotonGAceptar.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jBotonGAceptar.setText("Aceptar");
        jBotonGAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonGAceptarActionPerformed(evt);
            }
        });

        datosPers.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        datosPers.setText("Datos Personales:");

        antPatLabel.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        antPatLabel.setText("Antecedentes Patologicos:");

        diabetesRbutton.setText("Diabetes");

        hipertensionRButton.setText("Hipertension");
        hipertensionRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hipertensionRButtonActionPerformed(evt);
            }
        });

        tabacoRButton.setText("Tabaquismo");

        alcoholRButton.setText("Alcoholismo");

        otroAntLabel.setText("Otro(s):");

        otrosPatTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otrosPatTFieldActionPerformed(evt);
            }
        });

        alergiasLabel.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        alergiasLabel.setText("Alergias:");

        antNoPatLabel.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        antNoPatLabel.setText("Antecedentes No Patologicos:");

        pesoLabel.setText("Peso:");

        pesoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTFieldActionPerformed(evt);
            }
        });

        tallaLabel.setText("Talla:");

        sangreLabel.setText("Tipo Sangre:");

        sangreTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sangreTFieldActionPerformed(evt);
            }
        });

        frecCardLabel.setText("Frecuencia Cardiaca:");

        tensArtLabel.setText("Tension Art.:");

        tenArtTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenArtTFieldActionPerformed(evt);
            }
        });

        FrecRespLabel.setText("Frec. Respiratoria:");

        gineLabel.setText("Ginecologico:");

        otroNoPatLabel.setText("Otro(s): ");

        medicaAlergiasLabel.setText("Medicamentos:");

        mediTextArea.setColumns(20);
        mediTextArea.setRows(5);
        jScrollPane1.setViewportView(mediTextArea);

        sustanciasLabel.setText("Sustancias:");

        sustanciasTextArea.setColumns(20);
        sustanciasTextArea.setRows(5);
        jScrollPane2.setViewportView(sustanciasTextArea);

        alimentosLabel.setText("Alimentos:");

        alimentosTextArea.setColumns(20);
        alimentosTextArea.setRows(5);
        jScrollPane3.setViewportView(alimentosTextArea);

        otrasLabelAlergias.setFont(new java.awt.Font("Droid Sans", 1, 15)); // NOI18N
        otrasLabelAlergias.setText("Otra(s):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(antPatLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tabacoRButton)
                                    .addComponent(diabetesRbutton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hipertensionRButton)
                                    .addComponent(alcoholRButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(otroAntLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(otrosPatTField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(otrasLabelAlergias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(otrasAlergiasTField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(antNoPatLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(FrecRespLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(frecRespTField))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(frecCardTField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(pesoLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pesoTField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tallaLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tallaTField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(frecCardLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sangreLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(sangreTField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tensArtLabel)
                                                    .addComponent(gineLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tenArtTField, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                                    .addComponent(gineTField)))
                                            .addComponent(jBotonGAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(otroNoPatLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(otrosNoPatTFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datosPers)
                            .addComponent(alergiasLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medicaAlergiasLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sustanciasLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLOcupacion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLEmail)
                                                .addGap(46, 46, 46)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTFOcupacion, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                            .addComponent(jTFEmail)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLNombre)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLNac)
                                            .addGap(18, 18, 18)
                                            .addComponent(jCBdia, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCBmes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLTel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTFTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(129, 129, 129)
                                                .addComponent(jTFCel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jRBMasculino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRBFemenino)
                                                .addGap(132, 132, 132)
                                                .addComponent(jTFEstCiv, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLCel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLApellido1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLSexo)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLEstadoCiv))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTFAp1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLApellido2)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(alimentosLabel)))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(221, 221, 221)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosPers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellido1)
                    .addComponent(jTFAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellido2)
                    .addComponent(jTFAp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNac)
                    .addComponent(jCBdia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBmes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBMasculino)
                    .addComponent(jRBFemenino)
                    .addComponent(jLEstadoCiv)
                    .addComponent(jTFEstCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLOcupacion))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLCel)
                        .addComponent(jLTel)
                        .addComponent(jTFCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antPatLabel)
                    .addComponent(antNoPatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diabetesRbutton)
                    .addComponent(hipertensionRButton)
                    .addComponent(pesoLabel)
                    .addComponent(pesoTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tallaLabel)
                    .addComponent(tallaTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sangreLabel)
                    .addComponent(sangreTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabacoRButton)
                    .addComponent(alcoholRButton)
                    .addComponent(frecCardLabel)
                    .addComponent(frecCardTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tensArtLabel)
                    .addComponent(tenArtTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otroAntLabel)
                    .addComponent(otrosPatTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrecRespLabel)
                    .addComponent(frecRespTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gineLabel)
                    .addComponent(gineTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otroNoPatLabel)
                    .addComponent(otrosNoPatTFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alergiasLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicaAlergiasLabel)
                    .addComponent(sustanciasLabel)
                    .addComponent(alimentosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otrasLabelAlergias)
                            .addComponent(otrasAlergiasTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBotonGAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void SoloLetras(JTextField TF){
        TF.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent kE){
                char c = kE.getKeyChar();
                if(Character.isDigit(c)){
                    kE.consume();
                }
            }    
        });
    }
        
            public void SoloNumeros(JTextField TF){
                TF.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent kE){
                char c = kE.getKeyChar();
                if(!Character.isDigit(c)){
                  Toolkit.getDefaultToolkit().beep();
                    kE.consume();
                }
            }    
        });
    }
            
                public void SoloNumPuntuacion(JTextField TF){
        TF.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent kE){
                char c = kE.getKeyChar();
                if(Character.isLetter(c)){
                 Toolkit.getDefaultToolkit().beep();
                    kE.consume();
                }
            }    
        });
    }
    
    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jTFAp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAp1ActionPerformed

 
    
    private void jBotonGAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonGAceptarActionPerformed
        // TODO add your handling code here:
        //Ya abre la ventana de dos manera para modificar y para añadir solo
        //falta que este Action sepa que hacer y ademas del query necesario para realizar una modificacion
        if(getTipoOperacion() == 1){
            altaGUI();    
        }else if(getTipoOperacion() == 0){
            modificaGUI();
        }
    }//GEN-LAST:event_jBotonGAceptarActionPerformed

    private void jCBdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBdiaActionPerformed

    private void jCBmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBmesActionPerformed

    private void jRBFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFemeninoActionPerformed
        // TODO add your handling code here:
        if(jRBFemenino.isSelected()){
            jRBMasculino.setSelected(false);
        }
    }//GEN-LAST:event_jRBFemeninoActionPerformed

    private void jRBMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMasculinoActionPerformed
        // TODO add your handling code here:
        if(jRBMasculino.isSelected())
        {
            jRBFemenino.setSelected(false);
        }
    }//GEN-LAST:event_jRBMasculinoActionPerformed

    private void hipertensionRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hipertensionRButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hipertensionRButtonActionPerformed

    private void sangreTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sangreTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sangreTFieldActionPerformed

    private void otrosPatTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otrosPatTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otrosPatTFieldActionPerformed

    private void pesoTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTFieldActionPerformed

    private void tenArtTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenArtTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenArtTFieldActionPerformed

    private void jTFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreKeyTyped
        // TODO add your handling code here:
        SoloLetras(jTFNombre);
    }//GEN-LAST:event_jTFNombreKeyTyped

    private void jTFAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAnioKeyTyped
        // TODO add your handling code here:
        SoloNumeros(jTFAnio);
    }//GEN-LAST:event_jTFAnioKeyTyped

    
    public void llenarGUIModificaciones(ArrayList<String> alString){
        jTFNombre.setText(alString.get(1));
        jTFAp1.setText(alString.get(2));
        jTFAp2.setText(alString.get(3));
        if("0".equals(alString.get(4))){
            jRBFemenino.setSelected(true);
        }else{
            jRBMasculino.setSelected(true);
        }
        jTFEstCiv.setText(alString.get(5));
        jTFOcupacion.setText(alString.get(6));
        jTFTel.setText(alString.get(7));
        jTFCel.setText(alString.get(8));
        jTFEmail.setText(alString.get(9));
        String[] fechaNac = alString.get(10).split("/");
        jCBdia.setSelectedIndex(Integer.parseInt(fechaNac[0]));
        jCBmes.setSelectedIndex(Integer.parseInt(fechaNac[1]));
        jTFAnio.setText(fechaNac[2]);
        if("0".equals(alString.get(12))){
            diabetesRbutton.setSelected(false);
        }else{        
            diabetesRbutton.setSelected(true);
        }
        if("0".equals(alString.get(13))){
            hipertensionRButton.setSelected(false);
        }else{        
            hipertensionRButton.setSelected(true);
        }
        if("0".equals(alString.get(14))){
            tabacoRButton.setSelected(false);
        }else{        
            tabacoRButton.setSelected(true);
        }
        if("0".equals(alString.get(15))){
            alcoholRButton.setSelected(false);
        }else{        
            alcoholRButton.setSelected(true);
        }
        otrosPatTField.setText(alString.get(16));
        mediTextArea.setText(alString.get(17));
        sustanciasTextArea.setText(alString.get(18));
        alimentosTextArea.setText(alString.get(19));
        otrasAlergiasTField.setText(alString.get(20));
        gineTField.setText(alString.get(21));
        pesoTField.setText(alString.get(22));
        tallaTField.setText(alString.get(23));
        sangreTField.setText(alString.get(24));
        frecCardTField.setText(alString.get(25));
        tenArtTField.setText(alString.get(26));
        frecRespTField.setText(alString.get(27));
        otrosNoPatTFeld.setText(alString.get(28));
    }//metodo llenarGUIModificaciones
    
    
    //Incompleto falta hacer y arreglar lo de los RadioButton
      private void modificaGUI(){
      try{
        validame();    
        Paciente pacNew = new Paciente();
       
        //agregar datos para la tabla paciente
        pacNew.setNombrePac(jTFNombre.getText());
        pacNew.setApellidoPac1(jTFAp1.getText());
        pacNew.setApellidoPac2(jTFAp2.getText());  
        if(jRBMasculino.isSelected())    
            pacNew.setSexoPac(true);    
        else
            if(jRBFemenino.isSelected())                    
                pacNew.setSexoPac(false);
        pacNew.setEstadoCivPac(jTFEstCiv.getText());
        pacNew.setOcupacionPac(jTFOcupacion.getText());
        pacNew.setTelefono(Integer.parseInt(jTFTel.getText()));
        pacNew.setCelular(Long.parseLong(jTFCel.getText()));
        pacNew.setEmail(jTFEmail.getText());
        pacNew.setNacimiento(Integer.parseInt(String.valueOf(jCBdia.getSelectedItem())),
                Integer.parseInt(String.valueOf(jCBmes.getSelectedItem())), 
                Integer.parseInt(jTFAnio.getText()));
        
        //para tabla patologicos
        pacNew.getAntPatPac().setDiabetes(diabetesRbutton.isSelected());
        pacNew.getAntPatPac().setHipertension(hipertensionRButton.isSelected());
        pacNew.getAntPatPac().setTabaquismo(tabacoRButton.isSelected());
        pacNew.getAntPatPac().setAlcoholismo(alcoholRButton.isSelected());
        pacNew.getAntPatPac().setOtroAnt(otrosPatTField.getText());
        pacNew.getAntPatPac().getAlergiasPac().setMedicamento(mediTextArea.getText());
        pacNew.getAntPatPac().getAlergiasPac().setSustancias(sustanciasTextArea.getText());
        pacNew.getAntPatPac().getAlergiasPac().setAlimentos(alimentosTextArea.getText());
        pacNew.getAntPatPac().getAlergiasPac().setOtra(otrasAlergiasTField.getText());
       
        //para tabla nopatologicos
        pacNew.getAntNoPatPac().setGinecologico(gineTField.getText());
        pacNew.getAntNoPatPac().setPeso(Double.valueOf(pesoTField.getText()));
        pacNew.getAntNoPatPac().setTalla(Double.valueOf(tallaTField.getText()));
        pacNew.getAntNoPatPac().setTipoSangre(sangreTField.getText());
        pacNew.getAntNoPatPac().setFrecCard(Double.valueOf(frecCardTField.getText()));
        pacNew.getAntNoPatPac().setTensionArt(Double.valueOf(tenArtTField.getText()));
        pacNew.getAntNoPatPac().setFrecResp(Double.valueOf(frecRespTField.getText()));
        pacNew.getAntNoPatPac().setOtroAnt(otrosNoPatTFeld.getText());
        //Inserta Registro en tabla paciente        
        ConexionDB.updatePaciente(pacNew, getIdParaUpdate());
        this.dispose();
        }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Favor de escibir numeros en los campos Numericos", "Medicare dice:", JOptionPane.ERROR_MESSAGE);
        }catch (IllegalArgumentException e){
        JOptionPane.showMessageDialog(null, e.getMessage(), "Medicare dice:", JOptionPane.ERROR_MESSAGE);    
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Upps:\n"+e.getMessage(), "Medicare dice:", JOptionPane.ERROR_MESSAGE);
        } 
  }  

  
      private void altaGUI(){
          try{
              validame();    
              Paciente pacNew = new Paciente();
        
              //agregar datos para la tabla paciente
              pacNew.setNombrePac(jTFNombre.getText());
              pacNew.setApellidoPac1(jTFAp1.getText());
              pacNew.setApellidoPac2(jTFAp2.getText());  
              if(jRBMasculino.isSelected())   
                  pacNew.setSexoPac(true); 
              else
                  if(jRBFemenino.isSelected())
                      pacNew.setSexoPac(false);
              pacNew.setEstadoCivPac(jTFEstCiv.getText());
              pacNew.setOcupacionPac(jTFOcupacion.getText());        
              pacNew.setTelefono(Integer.parseInt(jTFTel.getText()));
              pacNew.setCelular(Long.parseLong(jTFCel.getText()));
              pacNew.setEmail(jTFEmail.getText());
              pacNew.setNacimiento(Integer.parseInt(String.valueOf(jCBdia.getSelectedItem())),
                Integer.parseInt(String.valueOf(jCBmes.getSelectedItem())), 
                Integer.parseInt(jTFAnio.getText()));
        
        //para tabla patologicos
        pacNew.getAntPatPac().setDiabetes(diabetesRbutton.isSelected());
        pacNew.getAntPatPac().setHipertension(hipertensionRButton.isSelected());
        pacNew.getAntPatPac().setTabaquismo(tabacoRButton.isSelected());
        pacNew.getAntPatPac().setAlcoholismo(alcoholRButton.isSelected());
        pacNew.getAntPatPac().setOtroAnt(otrosPatTField.getText());
        pacNew.getAntPatPac().getAlergiasPac().setMedicamento(mediTextArea.getText());
        pacNew.getAntPatPac().getAlergiasPac().setSustancias(sustanciasTextArea.getText());
        pacNew.getAntPatPac().getAlergiasPac().setAlimentos(alimentosTextArea.getText());
        pacNew.getAntPatPac().getAlergiasPac().setOtra(otrasAlergiasTField.getText());
       
        //para tabla nopatologicos
        pacNew.getAntNoPatPac().setGinecologico(gineTField.getText());
        pacNew.getAntNoPatPac().setPeso(Double.valueOf(pesoTField.getText()));
        pacNew.getAntNoPatPac().setTalla(Double.valueOf(tallaTField.getText()));
        pacNew.getAntNoPatPac().setTipoSangre(sangreTField.getText());
        pacNew.getAntNoPatPac().setFrecCard(Double.valueOf(frecCardTField.getText()));
        pacNew.getAntNoPatPac().setTensionArt(Double.valueOf(tenArtTField.getText()));
        pacNew.getAntNoPatPac().setFrecResp(Double.valueOf(frecRespTField.getText()));
        pacNew.getAntNoPatPac().setOtroAnt(otrosNoPatTFeld.getText());
        
        //Inserta Registro en tabla paciente        
        ConexionDB.altaPac(pacNew);
        int ultimo_id = ConexionDB.ultimoId();
        ConexionDB.altaPatologicos(pacNew, ultimo_id);
        ConexionDB.altaNoPatologicos(pacNew, ultimo_id);
        this.dispose();
        }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Favor de escibir numeros en los campos Numericos", "Medicare dice:", JOptionPane.ERROR_MESSAGE);
        }catch (IllegalArgumentException e){
        JOptionPane.showMessageDialog(null, e.getMessage(), "Medicare dice:", JOptionPane.ERROR_MESSAGE);    
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Upps:\n"+e.getMessage(), "Medicare dice:", JOptionPane.ERROR_MESSAGE);
        }
  }  
  
      /*Metodos de Validacion de Campos*/
    private void validame() throws Exception{
        String[] datos = {jTFNombre.getText(), jTFAp1.getText(), jTFAp2.getText(), 
            jTFEstCiv.getText(), jTFOcupacion.getText(), jTFTel.getText(), jTFCel.getText(),
            jTFEmail.getText(), jTFAnio.getText(), otrosPatTField.getText(), mediTextArea.getText(),
            sustanciasTextArea.getText(), alimentosTextArea.getText(), otrasAlergiasTField.getText(), 
            gineTField.getText(), pesoTField.getText(), tallaTField.getText(), sangreTField.getText(),
            frecCardTField.getText(), tenArtTField.getText(), frecRespTField.getText(), otrosNoPatTFeld.getText() };
        boolean sino = true;
        for (int i = 0; i <= datos.length - 1; i++) {
            if (datos[i].isEmpty()) {
                System.err.println("Algunos campos estan vacios");
                //sino = false;
                throw new Exception("Algun Campo de Texto se encuentra Vacio\n"
                        + "Escriba N/A si no aplica\nEn caso de que sea numerico '0'");
            }
        }
} 
 
    public void setIdParaUpdate(int idUpdate){
        idParaUpdate = idUpdate;
    }
    
    public int getIdParaUpdate(){
        return idParaUpdate;
    }
    
    public void setTipoOperacion(int tOp){
        tipoOperacion = tOp;
    }
    
    public int getTipoOperacion(){
        return tipoOperacion;
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAltas().setVisible(true);
            }
        });
    }
       
    private int tipoOperacion;
    private int idParaUpdate;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrecRespLabel;
    private javax.swing.JRadioButton alcoholRButton;
    private javax.swing.JLabel alergiasLabel;
    private javax.swing.JLabel alimentosLabel;
    private javax.swing.JTextArea alimentosTextArea;
    private javax.swing.JLabel antNoPatLabel;
    private javax.swing.JLabel antPatLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel datosPers;
    private javax.swing.JRadioButton diabetesRbutton;
    private javax.swing.JLabel frecCardLabel;
    private javax.swing.JTextField frecCardTField;
    private javax.swing.JTextField frecRespTField;
    private javax.swing.JLabel gineLabel;
    private javax.swing.JTextField gineTField;
    private javax.swing.JRadioButton hipertensionRButton;
    private javax.swing.JButton jBotonGAceptar;
    private javax.swing.JComboBox jCBdia;
    private javax.swing.JComboBox jCBmes;
    private javax.swing.JLabel jLApellido1;
    private javax.swing.JLabel jLApellido2;
    private javax.swing.JLabel jLCel;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLEstadoCiv;
    private javax.swing.JLabel jLNac;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLOcupacion;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLTel;
    private javax.swing.JRadioButton jRBFemenino;
    private javax.swing.JRadioButton jRBMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFAnio;
    private javax.swing.JTextField jTFAp1;
    private javax.swing.JTextField jTFAp2;
    private javax.swing.JTextField jTFCel;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEstCiv;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFOcupacion;
    private javax.swing.JTextField jTFTel;
    private javax.swing.JTextArea mediTextArea;
    private javax.swing.JLabel medicaAlergiasLabel;
    private javax.swing.JTextField otrasAlergiasTField;
    private javax.swing.JLabel otrasLabelAlergias;
    private javax.swing.JLabel otroAntLabel;
    private javax.swing.JLabel otroNoPatLabel;
    private javax.swing.JTextField otrosNoPatTFeld;
    private javax.swing.JTextField otrosPatTField;
    private javax.swing.JLabel pesoLabel;
    private javax.swing.JTextField pesoTField;
    private javax.swing.JLabel sangreLabel;
    private javax.swing.JTextField sangreTField;
    private javax.swing.JLabel sustanciasLabel;
    private javax.swing.JTextArea sustanciasTextArea;
    private javax.swing.JRadioButton tabacoRButton;
    private javax.swing.JLabel tallaLabel;
    private javax.swing.JTextField tallaTField;
    private javax.swing.JTextField tenArtTField;
    private javax.swing.JLabel tensArtLabel;
    // End of variables declaration//GEN-END:variables
}
